server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/obpam
    username: postgres
    password: mysecretpassword
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

logging.level.org.spring-framework.web: INFO
logging.level.org.hibernate: INFO
logging.level.com.obpam: INFO
